### ISSUE TITLE
JWFloatMax & JWIntegerMax wrong operation

### ISSUE THREAD

**Issue by S4Hyry** [jamesWalker55/comfyui-various#2]
Instead of Max, the node JWIntegerMax and JWFloatMax are doing min : 

**comfyui_primitive_ops.py**
`@generate_functional_node("jamesWalker55", "JWIntegerMax", "Integer Maximum")
def _(a: int = 0, b: int = 0) -> tuple[int]:
    return (min(a, b),)
`

`@generate_functional_node("jamesWalker55", "JWFloatMax", "Float Maximum")
def _(a: float = 0, b: float = 0) -> tuple[float]:
    return (min(a, b),)
`

**Comment by jamesWalker55** [comment]
Thanks, can't believe I missed that! I've just pushed a fix to the main branch.
